# Generated by Django 4.0.4 on 2022-05-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactstaff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
