# Generated by Django 4.0.4 on 2022-05-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0002_menuitem_menuitemid_menuitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='MenuItemId',
            new_name='MenuItem_Id',
        ),
    ]
